project_name: "vault-token-helper"

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    id: "vault-token-helper"
    main: ./cmd/vault-token-helper/main.go
    ldflags:
      - "-s -w"
      - "-extldflags '-static'"
      - "-X 'github.com/ilijamt/vault-token-helper.BuildVersion={{ .Version }}'"
      - "-X 'github.com/ilijamt/vault-token-helper.BuildHash={{ .FullCommit }}'"
      - "-X 'github.com/ilijamt/vault-token-helper.BuildDate={{ .Date }}'"
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ilijamt
    name: vault-token-helper

brews:
  - tap:
      owner: ilijamt
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/ilijamt/vault-token-helper
    description: A token helper is an external program that Vault calls to save, retrieve or erase a saved token.
    test: |
      system "#{bin}/vault-token-helper version"