name: build & test

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**.go"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        go: [1.18.x, 1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Display Go version
        run: go version
      - name: Install govulncheck@latest
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Scanning for dependencies with known vulnerabilities
        run: govulncheck -v ./... | tee -a govulncheck-${{ matrix.go }}.log
      - uses: actions/upload-artifact@v3
        with:
          name: govulncheck-${{ matrix.go }}
          path: govulncheck-${{ matrix.go }}.log
      - name: Build
        run: go build -v ./cmd/vault-token-helper
      - name: Test
        run: go test -v -json ./... | tee -a go-test-${{ matrix.go }}.json
      - uses: actions/upload-artifact@v3
        with:
          name: go-test-${{ matrix.go }}
          path: go-test-${{ matrix.go }}.json
